#!/bin/sh

mkdir -p /Library/Frameworks
cp -R -P Firebird.framework /Library/Frameworks
./addServEnt

chmod 777 /Library/Frameworks/Firebird.framework/Resources/English.lproj/var

chmod a+s /Library/Frameworks/Firebird.framework/Resources/bin/gds_drop
chmod a+s /Library/Frameworks/Firebird.framework/Resources/bin/gds_lock_mgr
chmod a+s /Library/Frameworks/Firebird.framework/Resources/bin/gds_inet_server


#
# If TCP is installed, update both services and servers databases
#
HUPNEEDED='n'	# Relevant to Classic only
if [ -f /etc/services ]; then
    grep -s gds_db /etc/services  > /dev/null 2>&1
    if test $? != 0 ; then
	HUPNEEDED='y'
        cat /etc/services /Library/Frameworks/Firebird.framework/Resources/English.lproj/var/services.isc > /etc/.interbase.temp.install.services
	mv /etc/.interbase.temp.install.services /etc/services
    fi
fi
if [ -f /etc/inetd.conf ]; then
    if [ "$SUPERSERVER" = "SUPERSERVER" ]; then
	# Remove gds_db service. We do not want gds_inet_server to be invoked
	cat /etc/inetd.conf | grep -v gds_db > /etc/.interbase.temp.install.inetd.conf
	mv /etc/.interbase.temp.install.inetd.conf /etc/inetd.conf
    else
	grep -s gds_db /etc/inetd.conf  > /dev/null 2>&1
	if test $? != 0 ; then
	    HUPNEEDED='y'
	    cat /etc/inetd.conf inetd.conf.isc > /etc/.interbase.temp.install.inetd.conf
	    mv /etc/.interbase.temp.install.inetd.conf /etc/inetd.conf
	fi
    fi
fi

if [ "$HUPNEEDED" = 'y' ]
then
    INETPID=`ps -axe | grep inetd | awk '{print $1}'`
    kill -HUP $INETPID
fi

