#!/bin/sh
#
# Nightly build script for Firebird Database
#
#
# Original by John Bellardo
#
cd ~/firebird
# mkdir nightly_build
cd nightly_build

(
    echo "####################### Firebird Nightly Build ######################"
    date
    echo "####################### Checking out sources from CVS ###############"
    cvs -z9 -d ":pserver:anonymous@cvs.firebird.sourceforge.net:/cvsroot/firebird" co interbase
    cd interbase
    date
    echo "####################### Configuring build ###########################"
    echo "" | ./Configure.sh DEV
    ./Configure_SetupEnv.sh
    date
    echo "####################### Building Firebird Classic ###################"
    make
    date
    echo "####################### Building Firebird Super Server ##############"
    make super_firebird
    cd ..
    date
    echo "####################### Nightly Build Complete ######################"
) 2>&1 | cat > build.log

mv interbase/interbase/DarwinCS.tar.gz .
mv interbase/interbase/DarwinSS.tar.gz .
rm -rf interbase

scp DarwinCS.tar.gz shell.sourceforge.net:DarwinCS.nightly.tar.gz
scp DarwinSS.tar.gz shell.sourceforge.net:DarwinSS.nightly.tar.gz
scp build.log shell.sourceforge.net:Darwin.nightly.log
