#!/bin/sh

. /etc/rc.common

##
# Start Firebird DB Server
##

# We don't want to add an entry to the hostconfig file yet, so we'll
# just comment out the code that understands the settings in hostconfig
#if [ "${FIREBIRDDB:=-NO-}" = "-YES-" ]; then
    if [ -f /Library/Frameworks/Firebird.framework/Resources/bin/ibmgr ]; then

        echo '/Library/Frameworks/Firebird.framework/Resources/bin/ibmgr -start -forever' | su firebird
    fi

# fi
